// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package zigibankgo

import (
	"context"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetAccountForUpdate(ctx context.Context, id int64) (Account, error)
	GetEntry(ctx context.Context, accountID int64) (Entry, error)
	GetTransfer(ctx context.Context, arg GetTransferParams) (Transfer, error)
	GetTransferFromId(ctx context.Context, id int64) (Transfer, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListEntries(ctx context.Context) ([]Entry, error)
	ListTransfers(ctx context.Context) ([]Transfer, error)
	UpdateBalance(ctx context.Context, arg UpdateBalanceParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
