name: Deploy images (recommended aws method)

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # Required for OIDC
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          role-to-assume: arn:aws:iam::665910433237:role/github-ci-recommended-track
          aws-region: eu-north-1

      - name: Log in to Amazon ECR
        run: aws ecr get-login-password --region eu-north-1 | \
             docker login --username AWS --password-stdin 665910433237.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build, Tag, and Push image
        run: |
          docker build -t my-app .
          docker tag my-app:latest 665910433237.dkr.ecr.eu-north-1.amazonaws.com/my-app:latest
          docker push 665910433237.dkr.ecr.eu-north-1.amazonaws.com/my-app:latest
